project:
  type: website
  output-dir: docs

website:
  title: "Technical Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: refrigerant-chemistry-adapt-vqe.qmd
        text: Chemistry ADAPT-VQE
      - href: llm-guided-adapt-vqe.qmd
        text: LLM-guided ADAPT-VQE
  page-navigation: true

format:
  html:
    theme: cerulean
