project:
  type: website
  output-dir: docs

website:
  title: "Technical Blog"
  navbar:
    left:
      - text: Home
        href: index.qmd
  page-navigation: true

format:
  html:
    theme: cerulean
    toc: true
    css: styles.css
