project:
  type: website
  output-dir: docs

website:
  title: "Technical Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
  page-navigation: true

format:
  html:
    theme: cerulean
